# Generated by Django 3.2.5 on 2021-07-21 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Marque')),
                ('abreviate', models.CharField(max_length=50, verbose_name='Abreviation Marque')),
                ('image', models.ImageField(max_length=300, upload_to='static/media/marque/', verbose_name='Logo Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Nom du matériel')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
                ('fabricant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.fabricant', verbose_name='Fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='TailleVetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Taille de vetement')),
                ('taille_fr', models.CharField(max_length=50, verbose_name='Taille FR de vetement')),
            ],
            options={
                'verbose_name': 'Taille de Vetement',
                'verbose_name_plural': 'Taille de Vetements',
            },
        ),
        migrations.CreateModel(
            name='TypeEnergieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
            ],
        ),
        migrations.CreateModel(
            name='Typevehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
                ('nbre_roue', models.IntegerField(verbose_name='Nombre de Roue Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='TypeVetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Libelle type de vetement')),
            ],
            options={
                'verbose_name': 'Taille de Vetement',
                'verbose_name_plural': 'Taille de Vetements',
            },
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference')),
                ('fabricat_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), materials.models.max_value_current_year], verbose_name='Année de fabrication')),
                ('description', models.TextField(verbose_name='Description')),
                ('valeur_cat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Catalogue')),
                ('valeur_achat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Achat')),
                ('valeur_residuel', models.IntegerField(blank=True, null=True, verbose_name='Valeur Residuel')),
                ('taille', models.CharField(max_length=50, verbose_name='Taille Vetement')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur Vetement')),
                ('materiel_utilisé', models.CharField(max_length=50, verbose_name='Materiel Utilisé')),
                ('taille_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.taillevetement', verbose_name='taille vetement')),
                ('type_vetement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typevetement', verbose_name='type vetement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference')),
                ('fabricat_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), materials.models.max_value_current_year], verbose_name='Année de fabrication')),
                ('description', models.TextField(verbose_name='Description')),
                ('valeur_cat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Catalogue')),
                ('valeur_achat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Achat')),
                ('valeur_residuel', models.IntegerField(blank=True, null=True, verbose_name='Valeur Residuel')),
                ('immatriculation', models.CharField(max_length=50, verbose_name='Immatriculation Vehicule')),
                ('last_kilometrage', models.IntegerField(verbose_name='Kilometrage Vehicule')),
                ('num_chassi', models.CharField(max_length=50, verbose_name='Numero de Chassi Vehicule')),
                ('couleur', models.CharField(max_length=50, verbose_name='Vehicule Vehicule')),
                ('nbre_porte', models.IntegerField(verbose_name='Nombre de Porte Vehicule')),
                ('type_transmissin', models.CharField(choices=[('1', 'Manuel'), ('2', 'Automatique')], max_length=1)),
                ('nbre_chevaux', models.IntegerField(verbose_name='Nombre de cheveaux')),
                ('puissance_fiscal', models.IntegerField(verbose_name='Puissance')),
                ('Typevehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typevehicule', verbose_name='Energie')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.model', verbose_name='Model')),
                ('type_energie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typeenergievehicule', verbose_name='Energie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference')),
                ('fabricat_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), materials.models.max_value_current_year], verbose_name='Année de fabrication')),
                ('description', models.TextField(verbose_name='Description')),
                ('valeur_cat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Catalogue')),
                ('valeur_achat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Achat')),
                ('valeur_residuel', models.IntegerField(blank=True, null=True, verbose_name='Valeur Residuel')),
                ('numero_serie', models.CharField(max_length=50, verbose_name='Nom du matériel')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.model', verbose_name='Model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_piece', models.CharField(max_length=50, verbose_name='Nom du matériel')),
                ('nbre_etage', models.CharField(max_length=50, verbose_name='Reference')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Latitude')),
                ('localite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.localite', verbose_name='Localite')),
            ],
        ),
    ]
