# Generated by Django 3.2.5 on 2021-10-25 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Libelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='reference')),
                ('numBonCmd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Bon de commande')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Bons de Livraison',
            },
        ),
        migrations.CreateModel(
            name='CategorieMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Mode acquistion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Reférence')),
                ('libelle', models.CharField(max_length=50, verbose_name='Nom court du lieu')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('Adresse', models.TextField(blank=True, max_length=50, null=True, verbose_name='adresse')),
                ('Tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EntrepotEnfant', to='materials.entrepots', verbose_name='Entrepot/Bureau Parent')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureau',
            },
        ),
        migrations.CreateModel(
            name='EtatMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Statut du Martéiel')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Marque')),
                ('abreviate', models.CharField(max_length=50, verbose_name='Abreviation Marque')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='static/media/marque/', verbose_name='Logo Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='localite')),
            ],
        ),
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference ')),
                ('fabricat_year', models.PositiveIntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(1984), materials.models.max_value_current_year], verbose_name='Année Acquisition')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('valeur_cat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Catalogue')),
                ('valeur_achat', models.IntegerField(blank=True, null=True, verbose_name='Valeur Achat')),
                ('valeur_residuel', models.IntegerField(blank=True, null=True, verbose_name='Valeur Residuel')),
                ('en_stock', models.BooleanField(default=True)),
                ('frabriquant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.fabricant', verbose_name='Marque')),
            ],
        ),
        migrations.CreateModel(
            name='ModeAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Mode acquistion')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
                ('fabricant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.fabricant', verbose_name='Fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('abrev', models.CharField(max_length=50, verbose_name='localite')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Libelle')),
                ('adresse', models.CharField(blank=True, max_length=50, null=True, verbose_name='adresse')),
                ('Tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
            ],
            options={
                'verbose_name': 'Structure Administrative',
                'verbose_name_plural': 'Structures Administrative',
            },
        ),
        migrations.CreateModel(
            name='TailleVetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Taille de vetement')),
                ('taille_fr', models.CharField(max_length=50, verbose_name='Taille FR de vetement')),
            ],
            options={
                'verbose_name': 'Taille de Vetement',
                'verbose_name_plural': 'Taille de Vetements',
            },
        ),
        migrations.CreateModel(
            name='TypeEnergieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
            ],
        ),
        migrations.CreateModel(
            name='Typevehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle Type Energie')),
                ('nbre_roue', models.IntegerField(verbose_name='Nombre de Roue Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='TypeVetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Libelle type de vetement')),
            ],
            options={
                'verbose_name': 'Type de Vetement',
                'verbose_name_plural': 'Type de Vetements',
            },
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=50, verbose_name='Taille Vetement')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur Vetement')),
                ('materiel_utilisé', models.CharField(max_length=50, verbose_name='Materiel Utilisé')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='materiel')),
                ('taille_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.taillevetement', verbose_name='taille vetement')),
                ('type_vetement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typevetement', verbose_name='type vetement')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True, verbose_name='Immatriculation Vehicule')),
                ('last_kilometrage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dernier kilometrage Vehicule (Km/Milles)')),
                ('num_chassi', models.CharField(max_length=50, unique=True, verbose_name='Numero de Chassi Vehicule')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur du Vehicule')),
                ('nbre_porte', models.IntegerField(default=5, verbose_name='Nombre de Porte Vehicule')),
                ('type_transmissin', models.CharField(choices=[('1', 'Manuel'), ('2', 'Automatique')], max_length=1)),
                ('nbre_chevaux', models.IntegerField(verbose_name='Nombre de cheveaux')),
                ('puissance_fiscal', models.IntegerField(verbose_name='Puissance')),
                ('Typevehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typevehicule', verbose_name='Type de Véhicule')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='materiel')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.model', verbose_name='Model')),
                ('type_energie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.typeenergievehicule', verbose_name="Type d'Energie")),
            ],
        ),
        migrations.CreateModel(
            name='StructureStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.CharField(max_length=64)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.structure')),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='materielStock',
            field=models.ManyToManyField(through='materials.StructureStock', to='materials.Materiels'),
        ),
        migrations.AddField(
            model_name='structure',
            name='structureParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structureEnfant', to='materials.structure'),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(verbose_name='Quantité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.entrepots', verbose_name='Entrepots')),
                ('etatMateriel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.etatmateriel', verbose_name='Etat')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='designation')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Nom du site ')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('Adresse', models.TextField(blank=True, max_length=50, null=True, verbose_name='adresse')),
                ('Tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('gps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cordonnée GPS')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=10, verbose_name='Ville')),
                ('etat', models.CharField(choices=[('OUVERT', 'OUVERT'), ('FERMER', 'FERMER')], default='OUVERT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EntrepotEnfant', to='materials.site', verbose_name='Site Parent ')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.pays', verbose_name='Pays')),
            ],
        ),
        migrations.AddField(
            model_name='materiels',
            name='mode_acquisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.modeacquisition', verbose_name='Mode Acquisition'),
        ),
        migrations.AddField(
            model_name='materiels',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.categoriemateriel', verbose_name='Catégorie Matériel'),
        ),
        migrations.AddField(
            model_name='entrepots',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='materials.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='Electronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nom du matériel')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='materiel')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.model', verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraisonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.CharField(max_length=50, verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonCommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.bonlivraison', verbose_name='bon de livraison')),
                ('etatMateriel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.etatmateriel', verbose_name='Etat')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='designation')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
            },
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='entrepot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.entrepots', verbose_name='Entrepots'),
        ),
        migrations.CreateModel(
            name='BonCommandeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.CharField(max_length=50, verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.boncommande', verbose_name='bon de commande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='designation')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
            },
        ),
        migrations.AddField(
            model_name='boncommande',
            name='structure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.structure', verbose_name='structure'),
        ),
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_piece', models.CharField(max_length=50, verbose_name='Nom du matériel')),
                ('nbre_etage', models.CharField(max_length=50, verbose_name='Reference')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Latitude')),
                ('localite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.localite', verbose_name='Localite')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiels', verbose_name='materiel')),
            ],
        ),
    ]
