# Generated by Django 3.2.5 on 2022-03-10 08:09

import django.core.validators
from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'BON ETAT'), ('2', 'EN PANNE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='materiels',
            name='en_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiels',
            name='fabricat_year',
            field=models.PositiveIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(1984), materials.models.max_value_current_year], verbose_name='Année Acquisition'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur du Vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nbre_chevaux',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de cheveaux'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_transmissin',
            field=models.CharField(blank=True, choices=[('1', 'Manuel'), ('2', 'Automatique')], max_length=1, null=True),
        ),
    ]
